### ISSUE TITLE
how can i build copay in macos?

### ISSUE THREAD

**Issue by mbunal** [bitpay/copay#11072]
i want to build my copay in mac mac. i tried
```
npm run clean-all
npm install
npm run apply:copay
npm run prepare:copay
npm run final:android
```
but i have an error while `npm install`:
```
82301 warn notsup Unsupported engine for karma-cli@1.0.1: wanted: {"node":"0.10 || 0.12 || 4 || 5 || 6"} (current: {"node":"14.7.0","npm":"6.14.7"})
82302 warn notsup Not compatible with your version of node/npm: karma-cli@1.0.1
82303 verbose notsup Not compatible with your version of node/npm: karma-cli@1.0.1
82303 verbose notsup Required: {"node":"0.10 || 0.12 || 4 || 5 || 6"}
82303 verbose notsup Actual:   {"npm":"6.14.7","node":"14.7.0"}
82304 warn notsup Unsupported engine for watchpack-chokidar2@2.0.0: wanted: {"node":"<8.10.0"} (current: {"node":"14.7.0","npm":"6.14.7"})
82305 warn notsup Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0
82306 verbose notsup Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0
82306 verbose notsup Required: {"node":"<8.10.0"}
82306 verbose notsup Actual:   {"npm":"6.14.7","node":"14.7.0"}
82307 warn @zxing/ngx-scanner@1.2.1 requires a peer of rxjs@^6.2.0 but none is installed. You must install peer dependencies yourself.
82308 warn ngx-barcode@0.2.4 requires a peer of @angular/core@^4.0.0 but none is installed. You must install peer dependencies yourself.
82309 warn awesome-typescript-loader@5.2.1 requires a peer of typescript@^2.7 || ^3 but none is installed. You must install peer dependencies yourself.
82310 warn mini-css-extract-plugin@0.8.0 requires a peer of webpack@^4.4.0 but none is installed. You must install peer dependencies yourself.
82311 warn @angular-devkit/build-webpack@0.12.4 requires a peer of webpack@^4.6.0 but none is installed. You must install peer dependencies yourself.
82312 warn @ngtools/webpack@7.2.4 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
82313 warn circular-dependency-plugin@5.0.2 requires a peer of webpack@>=4.0.1 but none is installed. You must install peer dependencies yourself.
82314 warn terser-webpack-plugin@1.2.1 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
82315 warn webpack-dev-middleware@3.4.0 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
82316 warn webpack-dev-server@3.1.14 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
82317 verbose stack Error: node-sass@4.10.0 postinstall: `node scripts/build.js`
82317 verbose stack Exit status 1
82317 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
82317 verbose stack     at EventEmitter.emit (events.js:314:20)
82317 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
82317 verbose stack     at ChildProcess.emit (events.js:314:20)
82317 verbose stack     at maybeClose (internal/child_process.js:1051:16)
82317 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
82318 verbose pkgid node-sass@4.10.0
82319 verbose cwd /Users/mbu/copay/10.1.2
82320 verbose Darwin 19.6.0
82321 verbose argv "/usr/local/Cellar/node/14.7.0/bin/node" "/usr/local/bin/npm" "install"
82322 verbose node v14.7.0
82323 verbose npm  v6.14.7
82324 error code ELIFECYCLE
82325 error errno 1
82326 error node-sass@4.10.0 postinstall: `node scripts/build.js`
82326 error Exit status 1
82327 error Failed at the node-sass@4.10.0 postinstall script.
82327 error This is probably not a problem with npm. There is likely additional logging output above.
82328 verbose exit [ 1, true ]
```

what i missed? can someone help me???

**Comment by skddc** [comment]
I have the same npm-install problem with both node.js stable (0.12) and latest (0.14), in a fresh clone with the `v10.1.1` checked out (as well as on the latest master commit).
