### ISSUE TITLE
GUI bug: cannot go back after selecting qr-scanner

### ISSUE THREAD

**Issue by themighty1** [bitpay/copay#3353]
using copay-linux64 1.41 (from github releases) when clicking the aim icon in the upper right corner I get on the console log:

[14332:1028/174813:ERROR:nw_shell.cc(335)] TypeError: Cannot read property 'stop' of undefined
    at _scanStop (file:///tmp/.org.chromium.Chromium.GfVD1Z/public/js/copay.js:1:17384)
    at Scope.$scope.cancel (file:///tmp/.org.chromium.Chromium.GfVD1Z/public/js/copay.js:1:18404)
    at _videoError (file:///tmp/.org.chromium.Chromium.GfVD1Z/public/js/copay.js:1:17746)
[14332:1028/174814:INFO:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'stop' of undefined", source: file:///tmp/.org.chromium.Chromium.GfVD1Z/public/js/copay.js (1)

pressing Close in the QR-Scanner window does nothing but spits out on the console

[14332:1028/174841:INFO:CONSOLE(1)] "", source: file:///tmp/.org.chromium.Chromium.GfVD1Z/public/js/copay.js (1)
[14332:1028/174841:INFO:CONSOLE(13)] ""Cannot read property 'stop' of undefined"", source: file:///tmp/.org.chromium.Chromium.GfVD1Z/public/lib/angular.js (13)

**Comment by cmgustavo** [comment]
I think there is a compatibility issue between versions of Chromium for Linux and the other platforms. Specifically with the `stop` function. I will check it out.

Thanks!

**Comment by cmgustavo** [comment]
Closes #3361
