### ISSUE TITLE
Version pinning breaks the compilation of the android-debug target

### ISSUE THREAD

**Issue by Giszmo** [bitpay/copay#3372]
ce5b154dfe59b299bc386b4ffc573e8a10ea86da introduced version pinning for cordova-plugin-email-composer.git
On my box it explodes there:

      Fetching plugin "https://github.com/katzer/cordova-plugin-email-composer.git" via git clone
      Error: git: Command failed with exit code 128 Error output:
      Cloning into '/tmp/git/1446174550683'...
      warning: Could not find remote branch f53df5c31c50d4f39d214a5cbe49abb0c5727a49 to clone.
      fatal: Remote branch f53df5c31c50d4f39d214a5cbe49abb0c5727a49 not found in upstream origin
          at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:134:23)
          at ChildProcess.emit (events.js:110:17)
          at maybeClose (child_process.js:1015:16)
          at Socket.<anonymous> (child_process.js:1183:11)
          at Socket.emit (events.js:107:17)
          at Pipe.close (net.js:485:12)
      * ERROR. Exiting...
      Makefile:53: recipe for target 'android-debug' failed
      make: *** [android-debug] Error 1

**Comment by cmgustavo** [comment]
Which version of Cordova are you using?

**Comment by Giszmo** [comment]
5.1.1

**Comment by matiu** [comment]
cannot reproduce (cordova 5.3.3)
