### ISSUE TITLE
"Illegal State" when signing tx

### ISSUE THREAD

**Issue by troggy** [bitpay/copay#3431]
Just installed Copay 1.4.3 Linux binary build.
Running it yields the following in console (excerpt):

````
[6239:1111/171603:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[6239:1111/171604:INFO:CONSOLE(90)] ""There was an error collecting entropy from the browser:"", source: file:///tmp/.org.chromium.Chromium.LD0moY/public/lib/angular.js (90)
[6239:1111/171604:INFO:CONSOLE(90)] "", source: file:///tmp/.org.chromium.Chromium.LD0moY/public/lib/angular.js (90)
````

Wallet starts fine, though I can backup my wallet only through "Advanced" preferences screen.

**The main issue**: it cannot sign transactions. When trying to sign, I receive error in logs:

````
[5626:1111/171118:ERROR:nw_shell.cc(335)] Error: Illegal State.
    at Object.validatorFunctions.checkState (file:///tmp/.org.chromium.Chromium.O9kN2c/public/lib/angular.js:74:17091)
    at Function.WalletUtils.signTxp (file:///tmp/.org.chromium.Chromium.O9kN2c/public/lib/angular.js:56:25738)
    at file:///tmp/.org.chromium.Chromium.O9kN2c/public/lib/angular.js:26:10849
    at API.getPayPro (file:///tmp/.org.chromium.Chromium.O9kN2c/public/lib/angular.js:26:10179)
    at API.signTxProposal (file:///tmp/.org.chromium.Chromium.O9kN2c/public/lib/angular.js:26:10625)
    at Object.root.signTxProposal (file:///tmp/.org.chromium.Chromium.O9kN2c/public/js/copay.js:3:16227)
    at signAndBroadcast (file:///tmp/.org.chromium.Chromium.O9kN2c/public/js/copay.js:6:28089)
    at file:///tmp/.org.chromium.Chromium.O9kN2c/public/js/copay.js:6:27220
    at file:///tmp/.org.chromium.Chromium.O9kN2c/public/lib/angular.js:26:8440
    at Object.callback (file:///tmp/.org.chromium.Chromium.O9kN2c/public/lib/angular.js:25:30869)
[5626:1111/171118:INFO:CONSOLE(74)] "Uncaught Error: Illegal State.", source: file:///tmp/.org.chromium.Chromium.O9kN2c/public/lib/angular.js (74)
````

**Comment by troggy** [comment]
I'm using default 1-of-1 livenet wallet.

**Comment by troggy** [comment]
Update: doesn't work for Chrome extension either (I'm importing same wallet)

**Comment by cmgustavo** [comment]
Could you try to update angular-bitcore-wallet-client with `bower i`? Check that your are using the latest version (v1.1.7)

**Comment by matiu** [comment]
Just to be sure:

This is a 1-1 wallet, livenet, created using the vanilla Linux binary, and you are trying to sign a TX creating fromt what same wallet, right?

**Comment by matiu** [comment]
PD: How do you imported the wallet chrome? Using mnemonics?

**Comment by troggy** [comment]
> This is a 1-1 wallet, livenet, created using the vanilla Linux binary, and you are trying to sign a TX creating fromt what same wallet, right?

Yes, except it wasn't created by this version of Copay — when I've started Copay it was already present, perhaps I created it some time ago with other version (it has one address created at September 5th, but that's all information I have).

> PD: How do you imported the wallet chrome? Using mnemonics?
Using json file

**Comment by troggy** [comment]
I can give you wallet id if it helps

**Comment by troggy** [comment]
Ok, found the date in logs. This wallet was created at 4th September 2015

**Comment by troggy** [comment]
Wallet has version "1.0.0". Copayer is of version "2" (integer). Pending txp that I cannot sign is of version "2.0.0"

**Comment by troggy** [comment]
Same wallet works in Copay 1.2.0 — I just have imported it and signed tx successfully.

**Comment by matiu** [comment]
we fund the error, is related to a new version of BWS we just isntalled. we
are fixing it now.

On Wed, Nov 11, 2015 at 12:09 PM, Kosta Korenkov <notifications@github.com>
wrote:

> Same wallet works in Copay 1.2.0 — I just have imported it and signed tx
> successfully.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3431#issuecomment-155807804>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by troggy** [comment]
Awesome!

**Comment by matiu** [comment]
it should be fixed now: Could you please try?

FYI: this is the installed fix:
https://github.com/bitpay/bitcore-wallet-service/pull/400

On Wed, Nov 11, 2015 at 12:15 PM, Kosta Korenkov <notifications@github.com>
wrote:

> Awesome!
>
> On 11 November 2015 at 18:14, Matias Alejo Garcia <
> notifications@github.com>
> wrote:
>
> > we fund the error, is related to a new version of BWS we just isntalled.
> we
> > are fixing it now.
> >
> > On Wed, Nov 11, 2015 at 12:09 PM, Kosta Korenkov <
> notifications@github.com
> > >
> > wrote:
> >
> > > Same wallet works in Copay 1.2.0 — I just have imported it and signed
> tx
> > > successfully.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/bitpay/copay/issues/3431#issuecomment-155807804>.
> > >
> >
> >
> >
> > --
> > Matías Alejo Garcia
> > @ematiu
> > Roads? Where we're going, we don't need roads!
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/bitpay/copay/issues/3431#issuecomment-155810747>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/copay/issues/3431#issuecomment-155811062>.
>



-- 
Matías Alejo Garcia
@ematiu
Roads? Where we're going, we don't need roads!

**Comment by troggy** [comment]
It works now. Thanks!
