### ISSUE TITLE
npm start fails - Warning: Error running grunt-browserify. Use --force to continue.

### ISSUE THREAD

**Issue by xelawafsTemp** [bitpay/copay#7081]
Environment:

**copay version: 3.8.2
node version: v8.4.0
npm version: 5.5.1
cordova version: 7.0.1**

Steps to produce

1. Clone copay
2. `npm run apply:copay` to install copay
3. `npm start` to test on browser

`npm start` fails after this warning:

```
Running "browserify:dist" (browserify) task
>> /app/copay/nightly/www/index.html:1
>> <!doctype html>
>> ^
>> ParseError: Unexpected token
Warning: Error running grunt-browserify. Use --force to continue.
```

npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.4.0/bin/node',
1 verbose cli   '/app/copay/nightly/node_modules/.bin/npm',
1 verbose cli   'run',
1 verbose cli   'build:www' ]
2 info using npm@2.15.12
3 info using node@v8.4.0
4 verbose run-script [ 'prebuild:www', 'build:www', 'postbuild:www' ]
5 info prebuild:www copay@3.8.6
6 info build:www copay@3.8.6
7 verbose unsafe-perm in lifecycle true
8 info copay@3.8.6 Failed to exec build:www script
9 verbose stack Error: copay@3.8.6 build:www: `grunt`
9 verbose stack Exit status 6
9 verbose stack     at EventEmitter.<anonymous> (/app/copay/nightly/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:125:13)
9 verbose stack     at EventEmitter.emit (events.js:213:7)
9 verbose stack     at ChildProcess.<anonymous> (/app/copay/nightly/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:125:13)
9 verbose stack     at ChildProcess.emit (events.js:213:7)
9 verbose stack     at maybeClose (internal/child_process.js:927:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid copay@3.8.6
11 verbose cwd /app/copay/nightly
12 error Darwin 16.7.0
13 error argv "/usr/local/Cellar/node/8.4.0/bin/node" "/app/copay/nightly/node_modules/.bin/npm" "run" "build:www"
14 error node v8.4.0
15 error npm  v2.15.12
16 error code ELIFECYCLE
17 error copay@3.8.6 build:www: `grunt`
17 error Exit status 6
18 error Failed at the copay@3.8.6 build:www script 'grunt'.
18 error This is most likely a problem with the copay package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     grunt
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs copay
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls copay
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**Comment by sskygod** [comment]
This issue has been discussed in ticket #7001. I don't know why lastest release still has this error. 
Is there any problem with testing?

I found another solution to this error in https://github.com/inbitcoin/asn1.js-rfc5280/commit/292d32838cf06b90501e82cf918e50ec8b03489e

**Comment by xelawafsTemp** [comment]
@sskygod thanks. I'm getting a blank page now. I've moved to [comment](https://github.com/bitpay/copay/issues/7001#issuecomment-343741690) on this issue #7001

**Comment by JDonadio** [comment]
Working now
