### ISSUE TITLE
Common wallet.Can not withdraw funds

### ISSUE THREAD

**Issue by Cvanci** [bitpay/copay#8716]
Hello!
I created a common wallet with my mother. I wrote down my password in 12 words, but when I sent the invitation to join, my mom's phone password went behind the screen, it simply was not visible. So I could not write the password and no invitations. Model phone Samsung Galaxy J1 (2016) model number SM-J120F. tell me please, money is lost or something can be done?

**Comment by BGalliotti** [comment]
Hello @Cvanci,

we cannot quite understand the issue.

The shared wallet flow is the following (2-2 example):
- Create a shared wallet on device 1
- Scan the QR code with device 2
- The shared wallet is complete, needs backup
- Separately backup the wallets in each of the devices
- Wallets ready to use

Please try to explain your issue in a clearer and more detailed fashion.

Thanks for reaching out to us.

Please let us know if you have any additional questions.
Kind regards.

**Comment by Cvanci** [comment]
Current operating system version for the device: Android 5.1.1
Current version of the wallet used: v3.14.2

Copay Session Logs
 Be careful, this could contain sensitive private data



[2018-05-30T17:47:13.581Z][info]Copay v3.14.2 #dc19bc0
[2018-05-30T17:47:13.592Z][info]Client: {"isAndroid":true,"isIOS":false,"isWP":false,"isSafari":false,"ua":"Mozilla/5.0 (Linux; Android 5.1.1; SM-J120F Build/LMY47X; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/55.0.2883.91 Mobile Safari/537.36","isCordova":true,"isMobile":true,"isDevel":false,"supportsTrezor":false,"versionIntelTEE":"","supportsIntelTEE":false}
[2018-05-30T17:47:13.599Z][debug]Using: FileStorage
[2018-05-30T17:47:14.266Z][info]Running head controller:Copay
[2018-05-30T17:47:14.370Z][debug]Route change from: -  to: starting
[2018-05-30T17:47:14.371Z][debug]            toParams:{}
[2018-05-30T17:47:14.372Z][debug]            fromParams:{}
[2018-05-30T17:47:14.580Z][info]Init profile...
[2018-05-30T17:47:15.066Z][debug]Got main dir: file:///data/data/com.bitpay.copay/files/
[2018-05-30T17:47:15.094Z][info]Adding Buy and Sell service:coinbase linked:false
[2018-05-30T17:47:15.098Z][debug]Got main dir: file:///data/data/com.bitpay.copay/files/
[2018-05-30T17:47:15.125Z][info]Adding Buy and Sell service:glidera linked:false
[2018-05-30T17:47:15.138Z][debug]Got main dir: file:///data/data/com.bitpay.copay/files/
[2018-05-30T17:47:15.160Z][info]Adding NextSteps entry:amazon
[2018-05-30T17:47:15.190Z][debug]Got main dir: file:///data/data/com.bitpay.copay/files/
[2018-05-30T17:47:15.209Z][info]Adding NextSteps entry:shapeshift
[2018-05-30T17:47:15.237Z][debug]Got main dir: file:///data/data/com.bitpay.copay/files/
[2018-05-30T17:47:15.278Z][info]Adding NextSteps entry:mercadoLibre
[2018-05-30T17:47:15.468Z][debug]Got main dir: file:///data/data/com.bitpay.copay/files/
[2018-05-30T17:47:15.543Z][debug]Profile is not encrypted
[2018-05-30T17:47:15.551Z][debug]Profile read
[2018-05-30T17:47:15.614Z][debug]Preferences read: {"limits":{"totalCopayers":6,"mPlusN":100},"bws":{"url":"https://bws.bitpay.com/bws/api"},"download":{"bitpay":{"url":"https://bitpay.com/wallet"},"copay":{"url":"https://copay.io/#download"}},"rateApp":{"bitpay":{"ios":"http://itunes.apple.com/WebObjects/MZStore.woa/wa/viewContentsUserReviews?id=1149581638&pageNumber=0&sortOrdering=2&type=Purple+Software&mt=8","android":"https://play.google.com/store/apps/details?id=com.bitpay.wallet","wp":""},"copay":{"ios":"http://itunes.apple.com/WebObjects/MZStore.woa/wa/viewContentsUserReviews?id=951330296&pageNumber=0&sortOrdering=2&type=Purple+Software&mt=8","android":"https://play.google.com/store/apps/details?id=com.bitpay.copay","wp":""}},"wallet":{"requiredCopayers":2,"totalCopayers":3,"spendUnconfirmed":false,"reconnectDelay":5000,"idleDurationMin":4,"settings":{"unitName":"BTC","unitToSatoshi":100000000,"unitDecimals":8,"unitCode":"btc","alternativeName":"Russian Ruble","alternativeIsoCode":"RUB"}},"lock":{"method":null,"value":null,"bannedUntil":null},"recentTransactions":{"enabled":true},"hideNextSteps":{"enabled":false},"rates":{"url":"https://insight.bitpay.com:443/api/rates"},"release":{"url":"https://api.github.com/repos/bitpay/copay/releases/latest"},"pushNotificationsEnabled":true,"confirmedTxsNotifications":{"enabled":true},"emailNotifications":{"enabled":false},"log":{"filter":"debug"},"bwsFor":{},"colorFor":{},"aliasFor":{},"emailFor":{}}
[2018-05-30T17:47:15.618Z][debug]Preferences read
[2018-05-30T17:47:15.634Z][info]Binding wallet:dfb59d48-9a4a-4290-8f42-959f5533d8b9 Validating?:false
[2018-05-30T17:47:15.658Z][debug]Wallet + dfb59d48-9a4a-4290-8f42-959f5533d8b9 status:undefined
[2018-05-30T17:47:15.662Z][info]Binding wallet:8f299482-3e4f-4e3a-9a69-da2bc6118959 Validating?:false
[2018-05-30T17:47:15.671Z][debug]Wallet + 8f299482-3e4f-4e3a-9a69-da2bc6118959 status:undefined
[2018-05-30T17:47:15.672Z][info]Bound 2 out of 2 wallets
[2018-05-30T17:47:15.681Z][debug]Profile loaded ... Starting UX.
[2018-05-30T17:47:15.683Z][debug]Trying to pre-initialize QRScanner.
[2018-05-30T17:47:15.729Z][debug]scannerService is reviewing platform capabilities...
[2018-05-30T17:47:15.732Z][debug]A camera is available to this app.
[2018-05-30T17:47:15.733Z][debug]Camera access is authorized.
[2018-05-30T17:47:15.734Z][debug]Support for opening device settings is available on this platform.
[2018-05-30T17:47:15.736Z][debug]A light is available on this platform.
[2018-05-30T17:47:15.737Z][debug]A second camera is available on this platform.
[2018-05-30T17:47:15.738Z][debug]Camera permission already granted.
[2018-05-30T17:47:15.740Z][debug]Initializing scanner...
[2018-05-30T17:47:15.812Z][debug]Route change from: starting  to: tabs.home
[2018-05-30T17:47:15.813Z][debug]            toParams:{"fromOnboarding":""}
[2018-05-30T17:47:15.814Z][debug]            fromParams:{}
[2018-05-30T17:47:15.849Z][debug]Setting default language: ru
[2018-05-30T17:47:15.863Z][debug]scannerService is reviewing platform capabilities...
[2018-05-30T17:47:15.864Z][debug]A camera is available to this app.
[2018-05-30T17:47:15.865Z][debug]Camera access is authorized.
[2018-05-30T17:47:15.866Z][debug]Support for opening device settings is available on this platform.
[2018-05-30T17:47:15.866Z][debug]A light is available on this platform.
[2018-05-30T17:47:15.867Z][debug]A second camera is available on this platform.
[2018-05-30T17:47:17.450Z][debug]buyAndSell Service, updating nextSteps. linked/total: 0/2
[2018-05-30T17:47:17.451Z][info]Adding NextSteps entry:buyandsell
[2018-05-30T17:47:17.514Z][debug]Initializing openURL
[2018-05-30T17:47:17.642Z][debug]Updating Status: Личный кошелёк null
[2018-05-30T17:47:17.877Z][debug]Updating Status: Mame null
[2018-05-30T17:47:17.995Z][debug]Starting push notification registration...
[2018-05-30T17:47:18.000Z][debug]startupService is showing the StatusBar...
[2018-05-30T17:47:18.004Z][debug]startupService is hiding the splashscreen...
[2018-05-30T17:47:18.177Z][error]Wallet service connection error.
[2018-05-30T17:47:18.179Z][error]Wallet service connection error.
[2018-05-30T17:47:18.224Z][debug]Get token for push notifications: d5EcBcpEIEg:APA91bF5ohRx0OkU5yUg2I0w05fFWJgA4zU6H3zCBy-lh-mhpSzu8mpuecErK6Z0OdJAHpUhfnuHRAV_6pdPRftCHM4q5xR0a2l4pZMOQjxpZI6mffRRT-IqXiyhY47VGEQhTMGr8ldr
[2018-05-30T17:47:19.157Z][error]Личный кошелёк: Subscription Push Notifications error.  {"message":"Wallet service connection error.","stack":"Wallet service connection error.\nError\n    at NodeError (file:///android_asset/www/lib/angular-components.js:67:5213)\n    at file:///android_asset/www/lib/angular-components.js:65:21757\n    at Request.callback (file:///android_asset/www/lib/angular-components.js:95:19632)\n    at Request.crossDomainError (file:///android_asset/www/lib/angular-components.js:95:19956)\n    at XMLHttpRequest.xhr.onreadystatechange (file:///android_asset/www/lib/angular-components.js:95:21061)"}
[2018-05-30T17:47:19.161Z][error]Mame: Subscription Push Notifications error.  {"message":"Wallet service connection error.","stack":"Wallet service connection error.\nError\n    at NodeError (file:///android_asset/www/lib/angular-components.js:67:5213)\n    at file:///android_asset/www/lib/angular-components.js:65:21757\n    at Request.callback (file:///android_asset/www/lib/angular-components.js:95:19632)\n    at Request.crossDomainError (file:///android_asset/www/lib/angular-components.js:95:19956)\n    at XMLHttpRequest.xhr.onreadystatechange (file:///android_asset/www/lib/angular-components.js:95:21061)"}
[2018-05-30T17:47:19.201Z][warn]Error updating notifications:bwc.ErrorCONNECTION_ERROR: Wallet service connection error.
[2018-05-30T17:47:19.204Z][warn]Error updating notifications:bwc.ErrorCONNECTION_ERROR: Wallet service connection error.
[2018-05-30T17:52:21.058Z][debug]Handle Resume @ openURL...
[2018-05-30T17:52:26.578Z][debug]Route change from: tabs.home  to: tabs.settings
[2018-05-30T17:52:26.579Z][debug]            toParams:{}
[2018-05-30T17:52:26.580Z][debug]            fromParams:{"fromOnboarding":""}
[2018-05-30T17:52:32.332Z][debug]Route change from: tabs.settings  to: tabs.about
[2018-05-30T17:52:32.334Z][debug]            toParams:{}
[2018-05-30T17:52:32.334Z][debug]            fromParams:{}
[2018-05-30T17:53:03.610Z][debug]Route change from: tabs.about  to: tabs.about.logs
[2018-05-30T17:53:03.611Z][debug]            toParams:{}
[2018-05-30T17:53:03.612Z][debug]            fromParams:{}
[2018-05-30T17:53:05.402Z][debug]Updating settings for wallet:dfb59d48-9a4a-4290-8f42-959f5533d8b9
[2018-05-30T17:53:05.408Z][debug]Updating settings for wallet:8f299482-3e4f-4e3a-9a69-da2bc6118959
[2018-05-30T17:53:05.409Z][debug]Storing Preferences {"limits":{"totalCopayers":6,"mPlusN":100},"bws":{"url":"https://bws.bitpay.com/bws/api"},"download":{"bitpay":{"url":"https://bitpay.com/wallet"},"copay":{"url":"https://copay.io/#download"}},"rateApp":{"bitpay":{"ios":"http://itunes.apple.com/WebObjects/MZStore.woa/wa/viewContentsUserReviews?id=1149581638&pageNumber=0&sortOrdering=2&type=Purple+Software&mt=8","android":"https://play.google.com/store/apps/details?id=com.bitpay.wallet","wp":""},"copay":{"ios":"http://itunes.apple.com/WebObjects/MZStore.woa/wa/viewContentsUserReviews?id=951330296&pageNumber=0&sortOrdering=2&type=Purple+Software&mt=8","android":"https://play.google.com/store/apps/details?id=com.bitpay.copay","wp":""}},"wallet":{"requiredCopayers":2,"totalCopayers":3,"spendUnconfirmed":false,"reconnectDelay":5000,"idleDurationMin":4,"settings":{"unitName":"BTC","unitToSatoshi":100000000,"unitDecimals":8,"unitCode":"btc","alternativeName":"Russian Ruble","alternativeIsoCode":"RUB"}},"lock":{"method":null,"value":null,"bannedUntil":null},"recentTransactions":{"enabled":true},"hideNextSteps":{"enabled":false},"rates":{"url":"https://insight.bitpay.com:443/api/rates"},"release":{"url":"https://api.github.com/repos/bitpay/copay/releases/latest"},"pushNotificationsEnabled":true,"confirmedTxsNotifications":{"enabled":true},"emailNotifications":{"enabled":false},"log":{"filter":"debug"}}
[2018-05-30T17:53:31.704Z][debug]Handle Resume @ openURL...

BitPay Wallet ID
 8f299482-3e4f-4e3a-9a69-da2bc6118959

I could not complete the backup on the second device because 12 words were out of sight.

**Comment by BGalliotti** [comment]
Hello @Cvanci ,

As we can see in your log, there is some kind of connection error. You are either not properly connected to the internet, or you have a wrong BWS configuration.  

However, that should not be related to your passphrase issue.
You are missing the backup as far as we understand. 

Before you back up the wallet in both devices, you will not be able to send funds.

**Please do not uninstall/update the wallet since your phone is not going to support the latest version and you will likely lose the money.**

Your problem is when you want to back up the wallet, you cannot properly see the word, right?

Please paste screenshots of what is going on. If it shows the words, try to block them (modify the image).
**We look forward to hearing from you.**

**Comment by BGalliotti** [comment]
Hello @Cvanci 

Thanks for reaching out to us.

**What do you mean by**
> I updated application after this case.

**You updated the application after being unable to see the words?**


Please let us know if you have any additional questions.
Kind regards.

**Comment by Cvanci** [comment]
Yes exactly

**Comment by BGalliotti** [comment]
Hello @Cvanci ,

So the problem now is that you have installed the latest version of the app (4.3.6) and it is not supported by your Android version so the app does not work properly and the words are not being seen, right?

If I am not understanding the issue, please try to explain it clearly and as deeply as possible. 
Also please paste:

- Your current Android version
- Your current wallet version

**Comment by Cvanci** [comment]
no. there are no words now. the wallet is gone, I can not make a backup copy.

**Comment by BGalliotti** [comment]
Hello @Cvanci ,

We are sorry you have had this bad experience.
We will be closing this ticket.

Please if you still need support, open a new one, we will be happy to help you.
Thanks.
Kind regards.
